version: "3"

services:
  daemon:
    image: kylemanna/bitcoind:latest 
    volumes:
      - "bitcoind_data:/bitcoin:rw"
    ports:
      - "8333:8333"
      - "8332:8332"
    restart: unless-stopped

volumes:
  bitcoind_data: {}