version: "3"

services:
  redis:
    image: redis:5-alpine3.9
    container_name: redis-node-0
    hostname: redis
    volumes:
      - "data:/data:rw"
      - "./redis.conf:/usr/local/etc/redis/redis.conf:ro"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - redis
    links:
      - redis:redis
    ports:
      - "8081:8081"

networks:
  redis:
    driver: bridge

volumes:
  data: {}