version: "3"

services:
  server:
    image: "gitlab/gitlab-ee:latest"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://127.0.0.1"
        gitlab_rails["lfs_enabled"] = true;
    restart: always
    ports:
      - "80:80"
      - "22:22"
    volumes:
      - "config:/etc/gitlab:rw"
      - "logs:/var/log/gitlab:rw"
      - "data:/var/opt/gitlab:rw"
      - "./.license_encryption_key.pub:/opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub"

volumes:
  config: {}
  logs: {}
  data: {}