version: "3"

services:
  watchtower:
    container_name: watchtower_server
    image: v2tec/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    restart: unless-stopped