version: "3"

services:
  watchtower:
    container_name: watchtower_server
    image: v2tec/watchtower
    command: --cleanup --schedule "0 0 0 * *" --debug
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: unless-stopped
