version: "3"

services:
  server:
    image: portainer/portainer:latest
    container_name: portainer_server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "config_data:/data:rw"
    ports:
      - "9000:9000"
    restart: unless-stopped

volumes:
  config_data: {}