version: "3"

services:
  server:
    image: rabbitmq:3-management-alpine
    hostname: "rabbit1"
    environment:
      - RABBITMQ_DEFAULT_USER: rabbit
      - RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq:rw"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  rabbitmq_data: {}