version: "3"

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres_server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "pg_data:/var/lib/postgresql/data/:rw"
    ports:
      - "55432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    container_name: pgadmin4_server
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - "pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "81:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  pg_data: {}
  pgadmin_data: {}
